region                     = "us-east-1"
stack_name                 = "qs-example"
vpc_cidr                   = "10.101.0.0/16"
azs                        = ["us-east-1a", "us-east-1b"]
vpc_cidrs                  = ["10.101.0.0/16"]
ecr_repository_url         = "quickysoft/sample-spring-boot-app"
environment_vars           = {}
backend_context_path       = "backend"
frontend1_context_path     = "frontend1"
frontend2_context_path     = "frontend2"
eventbridge_enabled        = true
event_notification_enabled = true
test_queue_name            = "qs-example-test-queue"
notification_queue_name    = "qs-example-notification-queue"
versioned                  = true
enable_dlq                 = true
visibility_timeout_seconds = 900 # 15 minutes
filter_prefix              = "upload/"
filter_suffix              = ".csv"
